version: "3.8"
services:
  eureka-server:
    image: crmcloud_eureka-server
    ports:
      - "8761:8761"
    networks:
      - crmcloud-network

  config-server:
    image: crmcloud_config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - crmcloud-network

  user-service:
    image: crmcloud_user-service
    ports:
      - "8060:8060"
    depends_on:
      - eureka-server
      - config-server
      - mongodb
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: "000001"
      QUEUE_NAME_CUSTOMER: customer-queue
      QUEUE_NAME_MESSAGE: message-queue
    networks:
      - crmcloud-network

  event-service:
    image: crmcloud_event-service
    ports:
      - "8070:8070"
    depends_on:
      - config-server
      - eureka-server
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: "000001"
      QUEUE_NAME_CUSTOMER: customer-queue
      QUEUE_NAME_MESSAGE: message-queue
    networks:
      - crmcloud-network

  edge-server:
    image: crmcloud_edge-server
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
      - user-service
      - event-service
    networks:
      - crmcloud-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: "000001"
      RABBITMQ_LOOPBACK_USERS: none
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - crmcloud-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "000000"
      MONGO_INITDB_DATABASE: crm_database
    volumes:
      - mongodb_data:/data/db
    networks:
      - crmcloud-network

networks:
 crmcloud-network:
      external: true

volumes:
  mongodb_data:
  rabbitmq_data: