apiVersion: v1                            # apiVersion은 v1을 사용
kind: Service                             # Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP                       # 사용 프로토콜
      port: 80
      targetPort: 8060
  type: ClusterIP                         # 클러스터 접속 가능한 가상IP 생성
