server:
  port: 8060

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: crm_database
      username: admin
      password: 000000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

