server:
  port: 8060

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://admin:000000@mongodb:27017/crm_database?authSource=admin

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:000001}

queue:
  customer: ${QUEUE_NAME_CUSTOMER:customer-queue}
  message: ${QUEUE_NAME_MESSAGE:message-queue}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

