server:
  port: 8080

spring:
  application:
    name: edge-server

  cloud:
    gateway:
      routes:
        - id: user-service
        - uri: lb://user-service
          predicates:
            - Path=/user-service/**

        - id: event-service
        - uri: lb://event-service
          predicates:
            - Path=/event-service/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

