server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/